from models.categoria import Categoria
from models.cliente import Cliente
from models.componente import Componente
from models.detalle_renta import DetalleRenta
from models.detalle_venta import DetalleVenta
from models.equipo import Equipo
from models.producto import Producto
from models.renta import Renta
from models.revision_equipo import RevisionEquipo
from models.rol import Rol
from models.usuario import Usuario
from models.venta import Venta
